In [1]:
import numpy as np

In [2]:
# E1: Given a 1D array, negate all elements which are between 3 and 8,
#  in place (not created a new array).
a = np.arange(11)
print('Original array : \n', a)
a[(3 < a) & (a <= 8)] *= -1
print('Negated array : \n', a)

Original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10]
Negated array : 
 [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [3]:
# E2: Create random vector of size 10 and replace the maximum value by 0
b = np.random.randn(10)
print('Original vector : \n', b)
b[b.argmax()] = 0
print('After replaced : \n', b)

Original vector : 
 [-1.24888204  1.13631191  1.09930192 -0.51716921 -1.20480278 -0.3213649
  0.54047948  0.64074863 -1.41836149  1.05428735]
After replaced : 
 [-1.24888204  0.          1.09930192 -0.51716921 -1.20480278 -0.3213649
  0.54047948  0.64074863 -1.41836149  1.05428735]


In [4]:
# E3: How to find common values between two arrays?
array1 = np.array([1, 2, 3, 4, 5, 6])
print("Array1: ", array1)
array2 = [2, 4, 6, 8]
print("Array2: ", array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [1 2 3 4 5 6]
Array2:  [2, 4, 6, 8]
Common values between two arrays:
[2 4 6]


In [5]:
# E4: Reverse a vector (first element becomes last)
c = np.arange(11)
print('Original vector : \n', c)
c = c[::-1]
print('Reversed vector : \n', c)


Original vector : 
 [ 0  1  2  3  4  5  6  7  8  9 10]
Reversed vector : 
 [10  9  8  7  6  5  4  3  2  1  0]


In [6]:
# E5: Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(9).reshape(3, 3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# E6: Find indices of non-zero elements from the array [1,2,0,0,4,0]
e = np.nonzero([1, 2, 0, 0, 4, 0])
print(e)

(array([0, 1, 4], dtype=int64),)


In [8]:
# E7: Create a 3x3x3 array with random values
f = np.random.random((3, 3, 3))
print('3x3x3 array with random values : \n', f)

3x3x3 array with random values : 
 [[[0.03215609 0.46241643 0.64656575]
  [0.90059465 0.0037424  0.71693686]
  [0.51645561 0.16694629 0.95271321]]

 [[0.95386424 0.45021092 0.73238518]
  [0.39914519 0.22130279 0.20218411]
  [0.57689157 0.34938678 0.59345265]]

 [[0.06350875 0.82233016 0.94485789]
  [0.28085276 0.98378663 0.42202431]
  [0.69456917 0.89760268 0.33216948]]]


In [9]:
# E8: Create a random vector of size 30 and find the mean value
g = np.random.randn(30)
print('Random vector : \n', g)
mv = g.mean()
print('Mean value : \n', mv)

Random vector : 
 [-0.65055105  1.50138748  0.47792004  1.42112145  0.45002976 -0.58546146
  1.2407577  -0.66952216 -1.14961354  0.99660993 -2.45774089  0.53836502
 -0.67420791 -1.41372446  1.73938923  0.238695    0.625661   -0.15775221
 -1.34703537  0.47737432  1.04667087 -0.30840321 -0.79212426 -1.25571929
 -0.62577683  0.30765741  1.36712491  0.83170396  0.69764726 -0.05576045]
Mean value : 
 0.06049074052793503


In [10]:
# E9: Create a 2d array with 1 on the border and 0 inside
h = np.ones((5, 5))
h[1:-1, 1:-1] = 0
print('2D array with 1 on the border and 0 inside : \n', h)

2D array with 1 on the border and 0 inside : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# E10: Find the index of x where the value at that index is closest to y.
x = np.random.randint(0, 100, 20)
print('Array x : \n', x)
y = np.random.uniform(0, 20)
print('Value y : \n', y)


def find_closest(array, value):
    idx = (np.abs(array - value)).argmin()
    return idx


print('Index of array where the value at that index is closest to the value y :', find_closest(x, y))

Array x : 
 [53 48 62 17 32 14 12 16 18 91 16 92 66 15 19 49 76 68 87 31]
Value y : 
 11.380854599271474
Index of array where the value at that index is closest to the value y : 6
